### ISSUE TITLE
Insert images

### ISSUE THREAD

**Issue by YogieAnamCara** [JohnTendik/jtrt-tables#28] opened 2016-12-19 06:13 UTC
Hi,

when clicking insert image from the menu, I'm getting the calculation in progress message and nothing more.

Cheers
Joerg

**Comment by JohnTendik** [comment] 2016-12-30 19:26
Ahh this is with the latest version I sent you, correct? The version with formulas enabled? 

I found out there is a conflict with the formula scripts and the image upload wp_media files. Not sure why and how but I will have to backlog Formulas until I can figure out the cause of this issue. 

Thanks
John

**Comment by JohnTendik** [comment] 2017-03-06 07:02
Closing this issue Joerg,

I'm hoping 4.1 has fixed this problem. Let me know if it still doesn't work. 

Thanks
John

**Closed by JohnTendik** 2017-03-06 07:02 UTC
