### ISSUE TITLE
Plugin does not show any tables and update is not working

### ISSUE THREAD

**Issue by kaidoparv** [JohnTendik/jtrt-tables#40] opened 2017-03-30 12:59 UTC
Using the last WP 4.7.3 and downloaded the last plugin version.
Created a table, but if I update it, nothing happens. Page is reloading but all the updates are lost.
Only the default table remains.
If I put the shortcode into the page, the result is:

Unfortunately we could not locate the table you're looking for.

Why? How can I use this plugin? It is really super as I have seen at the time, but how to make it work??

**Comment by JohnTendik** [comment] 2017-03-30 18:58
Hey, 

Are you getting any errors in the console at all? I doubt this is an issue with Javascript but if there is any error codes itd be nice to know what it is so I can narrow the issue down. 

Also, can you let me know what your PHP version is for your server and if you can get it, what the max file upload/execution limit is? I am not able to reproduce this issue in any of my test environments but it has come up multiple times for other people. My most intelligent guess would be that your server has a limit on how much info you can store at a time, it could be your DB or PHP settings. 

Thanks
John

**Comment by kaidoparv** [comment] 2017-03-30 19:20
Hi, no, the only thin I see in the console is:

jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
ping:1 URL-i ei saa laadida: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

but I do not think this is an issue.
and in the admin panel if I click JTRT table where I see all the table and if I click it to edit itm in the colsole I see this:

Uncaught ReferenceError: QTags is not defined
    at post.php?post=5933&action=edit&lang=et:2753
(anonymous) @ post.php?post=5933&action=edit&lang=et:2753

**Comment by JohnTendik** [comment] 2017-03-30 19:23
Hmm, 

Like I had assumed, these are issues from JTRT plugin. I don't think its a JS issue, most likely its something to do with your server setup. 

Are you by any chance running a wordpress multisite? 

Did you get my email ?

Thanks
John

**Comment by kaidoparv** [comment] 2017-03-30 19:24
sent you an email ;)

**Comment by JohnTendik** [comment] 2017-04-01 00:48
Ok sir, 

Thank you again for providing me access to test out the issue. I believe I have narrowed it down but I need you to help me out and test if it actually fixed anything. 

So from my troubleshooting I found out that my plugin wasn't able to execute the necessary saving functions before the post could update and therefor was only saving the default values. I have added a preventDefault on the publish button, hopefully this will force it to wait for my script to finish saving before it posts to the database. 

Are you comfortable with editing scripts? If so, can you try changing these lines of code from the file jtrt_tables/admin/js/vendor/jtrt-responsive-tables-class.js file? 

line 448
`//event.preventDefault();`
remove the comment blocks so simply change the line to this:
`event.preventDefault();`

then on line 531 at the end of the function block just before the } // end of handle on save
add this
`jQuery('#post').submit();`

Hopefully this will help with your saving issue. 

If you don't want to search around for line number and edit things out, you can simple delete everything in the jtrt-responsive-tables-class.js file and replace it with the following:
https://gist.github.com/JohnTendik/0476308ca22514236419e22d6ffe85ac


Let me know if this helps, I'd love to push this fix out to other users since many have experienced the same problem.

Thanks again for the support and letting me debug the issue on your website.

John

**Comment by kaidoparv** [comment] 2017-04-03 14:04
hi, nothing happend, still same result. it does not save the updates and page is not showing any tables

**Comment by JohnTendik** [comment] 2017-04-03 21:51
Hmm you say its not showing any tables? I'm guessing the save *does* happen but i feel like now youre getting a different error. Would you mind giving me access again for a little bit ? The fact that the tables are not showing means the data at least tried to save.

**Comment by kaidoparv** [comment] 2017-04-04 04:53
access sent, thanks!

**Comment by kaidoparv** [comment] 2017-04-08 15:23
any news?

**Comment by JohnTendik** [comment] 2018-06-29 03:34
@kaidoparv Sorry for the ghost town, are you still using the plugin and experiencing this issue? Im closing for now, please update to the latest version and let me know if the problem persists. 

Thanks
JT

**Closed by JohnTendik** 2018-06-29 03:34 UTC
